### PR TITLE
Add goreleaser Github Actions workflow

### PR DESCRIPTION
**Pull request by tomtaylor**

### CODE REVIEW

**Comment by tomtaylor** [comment]
Gonna have to merge this to see if it works...

**Comment by missinglink** [comment]
nice!

I noticed that the releases are `tar.gz` archives which contain just the binary and the readme.

It would probably be more convenient if they were just the binary, which would make it easier to just cURL them and use them directly on the command-line?

related: https://goreleaser.com/customization/archive/#disable-archiving

**Comment by tomtaylor** [comment]
Good shout - fixed in #10.

**Comment by thisisaaronland** [comment]
@tomtaylor When you have a few spare cycles would you be willing to add a readme/howto for setting up GH actions for this sort of thing to [whosonfirst-cookbook](https://github.com/whosonfirst/whosonfirst-cookbook) ?

**Pull request merged**
